import { saveAs } from "file-saver";
import JSZip from "jszip";
import type { ExportOptions, SliceManifestItem, SliceRect } from "../types";
import { cropImageToBlob } from "./crop";
import { normalizeFormat } from "./format";
import { generateSliceFileName } from "./naming";
import {
  generateCssSnippets,
  generateHtmlSnippets,
  generateJsonSnippets,
  generateVue3Snippets
} from "./snippets";

function ensureUniqueFileName(name: string, seen: Set<string>): string {
  if (!seen.has(name)) {
    seen.add(name);
    return name;
  }

  const dotIndex = name.lastIndexOf(".");
  const base = dotIndex >= 0 ? name.slice(0, dotIndex) : name;
  const extension = dotIndex >= 0 ? name.slice(dotIndex) : "";
  let next = 2;
  let candidate = `${base}-${next}${extension}`;
  while (seen.has(candidate)) {
    next += 1;
    candidate = `${base}-${next}${extension}`;
  }
  seen.add(candidate);
  return candidate;
}

function generateReadme(items: SliceManifestItem[]): string {
  return `# Image Slices

Generated by Frontend Image Slicer.

Total slices: ${items.length}

Use manifest.json for coordinates, dimensions, output files, and export scale.
`;
}

export async function exportSlicesToZip(
  image: HTMLImageElement,
  slices: SliceRect[],
  options: ExportOptions
): Promise<Blob> {
  const zip = new JSZip();
  const manifest: SliceManifestItem[] = [];
  const usedNames = new Set<string>();
  const validSlices = slices.filter(slice => slice.width > 0 && slice.height > 0);

  for (const [index, slice] of validSlices.entries()) {
    const fileName = ensureUniqueFileName(generateSliceFileName(slice, index, options), usedNames);
    const blob = await cropImageToBlob(image, slice, options);
    zip.file(`slices/${fileName}`, blob);
    manifest.push({
      id: slice.id,
      name: slice.name,
      file: `slices/${fileName}`,
      x: Math.round(slice.x),
      y: Math.round(slice.y),
      width: Math.round(slice.width),
      height: Math.round(slice.height),
      format: normalizeFormat(slice.format ?? options.format),
      scale: options.scale
    });
  }

  if (options.includeManifest) {
    zip.file("manifest.json", JSON.stringify(manifest, null, 2));
  }

  if (options.includeCodeSnippets) {
    zip.file("snippets/images.css", generateCssSnippets(manifest));
    zip.file("snippets/images.html", generateHtmlSnippets(manifest));
    zip.file("snippets/images.vue", generateVue3Snippets(manifest));
    zip.file("snippets/images.json", generateJsonSnippets(manifest));
  }

  if (options.includeReadme) {
    zip.file("README.md", generateReadme(manifest));
  }

  return zip.generateAsync({ type: "blob" });
}

export function downloadBlob(blob: Blob, fileName: string): void {
  saveAs(blob, fileName);
}
